Mc/p2022 1061 Register user action
intive/patronage22-dotnet-bialystok pull request #15
Opened 2022-03-02 16:23 UTC by Czopenchauer

Implementation of the feature "Register user action" that handle:
- Create new user
- Send confirmation email with the link to verify email
- Resend confirmation email
- Reset password
- Send reset password link to email
How CreateUser is supposed to work: create user -> send email with the link that redirect to HttpGet VerifyEmail in UserController.
How ResetPassword is supposed to work: reset password -> send email with the link that redirect to HttpGet PassResetPasswordCredentials in UserController. 
PassResetPasswordCredentials is supposed to give userId and token to FrontEnd so it can pass request to create new password at ResetPassword

2022-03-02 22:09 UTC, Archanial requested changes

2022-03-02 22:09 UTC, Archanial commented on src/Patronage.Api/Controllers/UserController.cs
> +        [SwaggerOperation(Summary = "Create new User and send confirmation email to User's email.")]
We have switched to xml comments instead of swagger annotations iirc

2022-03-02 22:09 UTC, Archanial commented on src/Patronage.Api/Controllers/UserController.cs
> +            if (!result.Result)
Can the result be null? What happens if there is no db connection?

2022-03-02 22:09 UTC, Archanial commented on src/Patronage.Api/Program.cs
> +    }
This should be moved to some kind of init function in the service itself

2022-03-02 22:09 UTC, Archanial commented on src/Patronage.Contracts/ModelDtos/User/CreateUserDto.cs
> +        public string Email { get; set; }
Warnings, use either null! or string?

2022-03-02 22:09 UTC, Archanial commented on src/Patronage.Contracts/ModelDtos/User/UserDto.cs
> +        public string Id { get; set; }
Warnings

2022-03-03 11:32 UTC, mateuszgiedzinski commented on src/Patronage.Api/Program.cs
> +    }
Write extension method for Services (IServiceCollection i think) end Name it AddEmailService(). Then code in program.cs should be like that 
builder.Services.AddEmailService();
We also should have such a methods for database and other services which configuration is large. 
Keep program.cs as simple as possible.

2022-03-03 14:38 UTC, Czopenchauer commented on src/Patronage.Api/Controllers/UserController.cs
> +            if (!result.Result)
I'm not entirly sure what do you mean by "result can be null". Can you elaborate? Answering your second question, If there is no db connection, an error is thrown which is handled by ErrorHandlingMiddleware

2022-03-07 18:17 UTC, Archanial approved these changes

2022-03-07 18:20 UTC, merged