Mc/p2022 1588
intive/patronage22-dotnet-bialystok pull request #20
Opened 2022-03-12 12:54 UTC by Czopenchauer

Change Swagger Annotations to xml comments.
Make BoardController match routing convention i.e api/[controllerName]/update/{id} in place of api/[controllerName]/update

2022-03-12 19:05 UTC, Papuzka approved these changes

2022-03-12 19:13 UTC, xBonioo requested changes

2022-03-12 19:13 UTC, xBonioo commented on src/Patronage.Api/Controllers/BoardController.cs
> +                    ResponseCode = StatusCodes.Status500InternalServerError,
In the comment above, you enter the code 400 and below you return the code 500

2022-03-12 19:13 UTC, xBonioo commented on src/Patronage.Api/Validators/Board/UpdateBoardValidator.cs
> +                .NotEmpty().WithMessage("Can not be empty.")
NotNull() and NotEmpy() have better message than 'Can not be null' and 'Can not be empty'

2022-03-12 19:45 UTC, xBonioo commented on src/Patronage.Api/Controllers/BoardController.cs
> +                    ResponseCode = StatusCodes.Status500InternalServerError,
In the comment above, you enter the code 400 and below you return the code 500

2022-03-12 19:45 UTC, xBonioo commented on src/Patronage.Api/Validators/Board/UpdateBoardValidator.cs
> +                .NotEmpty().WithMessage("Can not be empty.")
NotNull() and NotEmpty() have better message than 'Can not be null' and 'Can not be empty'

2022-03-13 13:36 UTC, Czopenchauer commented on src/Patronage.Api/Controllers/BoardController.cs
> +                    ResponseCode = StatusCodes.Status500InternalServerError,
Good catch. I didn't see that

2022-03-13 13:40 UTC, xBonioo approved these changes

2022-03-13 20:08 UTC, mateuszgiedzinski requested changes

2022-03-13 20:08 UTC, mateuszgiedzinski commented on src/Patronage.Api/Validators/Board/UpdateBoardValidator.cs
> +                .MaximumLength(1024).WithMessage("Can not exceed 1024 characters.")
Validator sepcified in FluentValidation has own messages better than specified by you.  Please read about this in doc. Try to learn using documentation.

2022-03-13 20:08 UTC, mateuszgiedzinski commented on src/Patronage.DataAccess/Services/BoardService.cs
> +            var board = await tableContext.Boards.FirstOrDefaultAsync(x => x.Id == id);
I think we have method GetById or GetByKey in this service

2022-03-13 20:08 UTC, mateuszgiedzinski commented on src/Patronage.DataAccess/Services/BoardService.cs
> +            var board = await tableContext.Boards.FirstOrDefaultAsync(x => x.Id == id);
If not maybe we need this. We also could create interface named IKeyedEntity with int Id {ge;set;} property. 
Then we could add extension methods  and use it like tableContext.Boards.GetByIdAsync(id);

2022-03-13 21:21 UTC, Czopenchauer commented on src/Patronage.Api/Controllers/BoardController.cs
> +        /// <response code="400">Board could not be created.</response>
To be honest I'm not entirely sure what info should I add. 400 is returned when entity was created but could not be saved to database. Perhaps instead of 400, I should throw exception?

2022-03-13 21:36 UTC, Czopenchauer commented on src/Patronage.Api/Controllers/BoardController.cs
> +        /// <param name="filter">Object created from query containing Alias, Name and Descripion.</param>
It will be "and". I'll add more descriptive comment

2022-03-13 21:40 UTC, Czopenchauer commented on src/Patronage.Api/Controllers/BoardController.cs
>                  {
If we take into consideration other possibilities such as problems with database I don't think we can retrieve this information from bool. So instead of trying that could I change method in BoardService that return false if there's no board, true if everything went smoothly and throw exception in case changes could not be saved to database?

2022-03-13 21:41 UTC, Czopenchauer commented on src/Patronage.DataAccess/Services/BoardService.cs
> +            var board = await tableContext.Boards.FirstOrDefaultAsync(x => x.Id == id);
We have `IEntityService` with method `GetByIdAsync`. I'll add it

2022-03-15 23:23 UTC, merged