Ks/p2022 1567
intive/patronage22-dotnet-bialystok pull request #21
Opened 2022-03-12 13:27 UTC by xBonioo

Adding comments to an issue
- Issues Comment Controller with CRUD
- Validators
- Comment model
- Comment dtos
- Service
- MediatR
- Migrations (MsSQL & Postgre)

2022-03-12 19:22 UTC, Papuzka commented on src/Patronage.Api/Validators/Comments/CommentDtoValidator.cs
> +                .NotNull()
Shouldn't you return a message when empty or null?

2022-03-12 19:25 UTC, xBonioo commented on src/Patronage.Api/Validators/Comments/CommentDtoValidator.cs
> +                .NotNull()
Mateusz said in my last pr that this function has a better message

2022-03-12 20:00 UTC, Papuzka commented on src/Patronage.Api/Validators/Comments/CommentDtoValidator.cs
> +                .NotNull()
Ok 👍

2022-03-13 14:23 UTC, Czopenchauer requested changes

2022-03-13 14:23 UTC, Czopenchauer commented on src/Patronage.Api/Validators/Comments/CommentQueryValidator.cs
> +        private int[] allowedPageSizes = new[] { 5, 10, 15 };
I don't know if I understand it properly so correct me if I'm wrong. We can only request list of size 5, 10 or 15 right? If yes wouldn't it be better to just set a limit "not greater than 15"?

2022-03-13 14:23 UTC, Czopenchauer commented on src/Patronage.Contracts/ModelDtos/Issues/IssueDto.cs
> +        public List<Comment> Comments { get; set; }
```suggestion
        public List<Comment>? Comments { get; set; }
```

2022-03-13 14:23 UTC, Czopenchauer commented on src/Patronage.DataAccess/Services/CommentService.cs
> +            var items = await comments.ToArrayAsync();
```suggestion
            var items = await comments.Select(x => new CommentDto(x).ToListAsync();
```
Instead of foreach loop. (Check if it works first, I'm just suggesting different approach)

2022-03-13 14:23 UTC, Czopenchauer commented on src/Patronage.Models/Comment.cs
> +        public string ApplicationUserId { get; set; } = null!;
(I can be wrong with this so ask Mateusz or Marek to confirm)
To form relationship you also need to add ApplicationUser as navigation property:
`public ApplicationUser User { get; set; } = null!;`
The same with the Issue

2022-03-13 14:23 UTC, Czopenchauer commented on src/Patronage.Models/TableContext.cs
> +        modelBuilder.Entity<Comment>()
(It's related to Issue entity. Once again ask Mateusz or Marek to confirm if I'm correct)
Shouldn't you declare relation? I believe it will be one to many between Issue and Comment
https://docs.microsoft.com/en-us/ef/core/modeling/relationships?tabs=fluent-api%2Cfluent-api-simple-key%2Csimple-key#manual-configuration

2022-03-13 14:23 UTC, Czopenchauer commented on src/Patronage.DataAccess/Services/IssueService.cs
> +                .Include(x => x.Comment)
I don't think we have to Include comments to all issue. It can become quite large so I think it will be better to remove that line and return comments when you request Issue by id

2022-03-13 17:48 UTC, xBonioo commented on src/Patronage.Contracts/ModelDtos/Issues/IssueDto.cs
> +        public List<Comment> Comments { get; set; }
OK, I will apply this in a new commit.
It didn't work for me before, now I don't know why.

2022-03-13 17:51 UTC, xBonioo commented on src/Patronage.Api/Validators/Comments/CommentQueryValidator.cs
> +        private int[] allowedPageSizes = new[] { 5, 10, 15 };
The site usually has every five regularly, so I used that too, change it?
This code is too in IssueQueryValidator.

2022-03-13 17:54 UTC, xBonioo commented on src/Patronage.Api/MediatR/Comment/Commands/Create/CreateCommentCommandHandler.cs
> +            return await _commentService.CreateAsync(new BaseCommentDto(request.Data));
Yes, it works. I did this before and just copied it from issue. I swapped both.

2022-03-13 17:57 UTC, xBonioo commented on src/Patronage.DataAccess/Services/IssueService.cs
> +                .Include(x => x.Comment)
Okey, it will be in new commit.

2022-03-13 19:32 UTC, mateuszgiedzinski commented on src/Patronage.Api/Validators/Comments/CommentQueryValidator.cs
> +        private int[] allowedPageSizes = new[] { 5, 10, 15 };
I recommend to create some static readonly property for AllowedPageSize.

2022-03-13 19:39 UTC, mateuszgiedzinski commented on src/Patronage.Models/Comment.cs
> +        public string ApplicationUserId { get; set; } = null!;
Navigation properties is optional for entities. but you must specify foreign keys.

2022-03-13 19:50 UTC, mateuszgiedzinski requested changes

2022-03-13 19:50 UTC, mateuszgiedzinski commented on src/Patronage.Models/TableContext.cs
> +        modelBuilder.Entity<Comment>()
You're right @Czopenchauer . We must specify relationship between entities. Navigation properties are optional but foreign keys are required.

2022-03-13 19:50 UTC, mateuszgiedzinski commented on src/Patronage.Api/Controllers/IssuesCommentController.cs
> +        /// <response code="500">Sorry. Try it later.</response>
Try to write better comment. Think about it  as what you want to read in some library/api documentation.
/// <response code="500">Sorry. Try it later.</response> - This comment made me laugh

2022-03-13 19:50 UTC, mateuszgiedzinski commented on src/Patronage.Api/Controllers/IssuesCommentController.cs
> +        /// <response code="500">Sorry. Try it later.</response>
Maybe add a reason why we could get 500

2022-03-14 07:23 UTC, xBonioo commented on src/Patronage.Models/TableContext.cs
> +        modelBuilder.Entity<Comment>()
Table comments have fk in ApplicationUserId and IssueId. I will show it on today in daily meet.

2022-03-14 08:03 UTC, xBonioo commented on src/Patronage.DataAccess/Services/CommentService.cs
> +            var items = await comments.ToArrayAsync();
Done.

2022-03-16 15:33 UTC, merged