P2022 1691, P2022 1694, P2022 1820
intive/patronage22-dotnet-bialystok pull request #27
Opened 2022-03-22 10:45 UTC by xBonioo

- Joining GetAll and GetById Board Status to one function with filter
- Change return board list
- Add xml comments to BoardStatusController
- Add query extension method to Board and BoardStatus
- Create BaseBoardDto
- Add return boards by project ID

2022-03-23 13:44 UTC, Dimethiconol commented on src/Patronage.Api/MediatR/BoardStatus/Queries/GetAllBoardStatusQuery.cs
> -    public record GetAllBoardStatusQuery() : IRequest<IEnumerable<BoardStatusDto>>;
I think it could be changed like that:
public record GetAllBoardStatusQuery(FilterBoardStatusDto filter) : IRequest<IEnumerable<BoardStatusDto>>;

Nevertheless i don't tell that with class is bad, or at least worse

2022-03-23 14:10 UTC, Dimethiconol commented on src/Patronage.Api/Validators/BoardStatus/CreateBoardStatusValidator.cs
> -            RuleFor(s => s.Dto.StatusId).Must(NotLessThan).WithMessage("StatusId must be greater than 0").Must(ExistsStatusId).WithMessage("StatusId does not exist");
Now there is not returned message what exactly was entered not properely.
There were "BoardId does not exist" or "StatusId does not exist". Now it is more generic "Error creating BoardStatus" for both cases. I dont know how is better.

2022-03-24 17:35 UTC, xBonioo commented on src/Patronage.Api/Validators/BoardStatus/CreateBoardStatusValidator.cs
> -            RuleFor(s => s.Dto.StatusId).Must(NotLessThan).WithMessage("StatusId must be greater than 0").Must(ExistsStatusId).WithMessage("StatusId does not exist");
I deleted too much, I will add this is new commit.

2022-03-24 17:37 UTC, xBonioo commented on src/Patronage.Api/MediatR/BoardStatus/Queries/GetAllBoardStatusQuery.cs
> -    public record GetAllBoardStatusQuery() : IRequest<IEnumerable<BoardStatusDto>>;
But there is PageResult which is a generic class.

2022-03-26 00:18 UTC, Archanial requested changes

2022-03-26 00:18 UTC, Archanial commented on src/Patronage.Api/Controllers/BoardStatusController.cs
> +                    Message = $"There's no board status"
```suggestion
                    Message = $"BoardStatus not found"
```

2022-03-26 00:18 UTC, Archanial commented on src/Patronage.Api/MediatR/BoardStatus/Commands/CreateBoardStatusCommand.cs
> +        public BoardStatusDto Dto { get; set; } = null!;
```suggestion
        public BoardStatusDto Dto { get; set; }
```
null isn't needed if we always set the Dto in constructor

2022-03-26 00:18 UTC, Archanial commented on src/Patronage.Api/Validators/BoardStatus/BoardStatusQueryValidator.cs
> +}
duplicated code

2022-03-26 00:18 UTC, Archanial commented on src/Patronage.Contracts/Helpers/BoardQueryExtensions.cs
> +            return value;
The value returned here can be an empty set, do we consider this possibility?

2022-03-26 00:18 UTC, Archanial commented on src/Patronage.Contracts/Helpers/BoardStatusQueryExtensions.cs
> +            return value;
same as above

2022-03-26 00:18 UTC, Archanial commented on src/Patronage.DataAccess/Services/BoardService.cs
> +                ProjectId = request!.ProjectId,
first you check for request then you assume it exists?

2022-03-26 10:05 UTC, xBonioo commented on src/Patronage.Api/MediatR/BoardStatus/Commands/CreateBoardStatusCommand.cs
> +        public BoardStatusDto Dto { get; set; } = null!;
Okey, i will delete this.

2022-03-26 10:10 UTC, xBonioo commented on src/Patronage.Api/Validators/BoardStatus/BoardStatusQueryValidator.cs
> +}
What duplication? I need to make a new validator for a new class. I am making a new file to be able to extend this validator in the future.

2022-03-26 10:11 UTC, xBonioo commented on src/Patronage.Api/Controllers/BoardStatusController.cs
> +                    Message = $"There's no board status"
Ok, i will change

2022-03-26 10:13 UTC, xBonioo commented on src/Patronage.Contracts/Helpers/BoardQueryExtensions.cs
> +            return value;
The value will not be empty. Returns the same content as received.

2022-03-26 10:14 UTC, xBonioo commented on src/Patronage.Contracts/Helpers/BoardStatusQueryExtensions.cs
> +            return value;
same answer as above

2022-03-26 10:15 UTC, xBonioo commented on src/Patronage.DataAccess/Services/BoardService.cs
> +                ProjectId = request!.ProjectId,
I don't understand your comment.

2022-03-26 16:57 UTC, Czopenchauer commented on src/Patronage.Api/Controllers/BoardStatusController.cs
> +        /// <response code="404">No BoardStatus found in the database.</response>
Imo passive voice would sound better.
Instead of "No BoardStatus found in the database." -> "No BoardStatuses have been/ were found in the database"

2022-03-26 16:57 UTC, Czopenchauer commented on src/Patronage.DataAccess/Services/BoardStatusService.cs
>                  catch (Exception)
Get rid of try catch and let ErrorHandlingMiddleware handle exception. Right now you return 400 BadRequest when there's problem with SaveChangesAsync and that's simply not true. It's database problem not with a client's request.
If you want o check if changes have been saved use: `if(await _dbContext.SaveChangesAsync() > 0)`

2022-03-26 17:29 UTC, merged

2022-03-26 19:36 UTC, Archanial commented on src/Patronage.Contracts/Helpers/BoardStatusQueryExtensions.cs
> +            return value;
If you filter for, let's say Id, and there is nothing with this id in the given set, the returning set should be empty, if I understand this right.