KD/P2022 468 469 project controller and service
intive/patronage22-dotnet-bialystok pull request #8
Opened 2022-02-20 14:25 UTC by Dimethiconol

It is supossed to be full CRUD of Projects. The following things has been changed from the current implementation:
- controllers are asynchronous now
- the AutoMapper isn't used
- catalogue arrangement of Project MediatR classes is improved
- BaseResponse class is used as a model resoponse in project controller
- partial update works as intended
- validation for crating and updating projects is working again

2022-02-20 21:56 UTC, mateuszgiedzinski requested changes

2022-02-20 21:56 UTC, mateuszgiedzinski commented on src/Patronage.DataAccess/Services/ProjectService.cs
> -            var projects = _dbContext
check string empty outside linq where statement
`query = _dbContext.Projects;
if(!searchProject.IsNullOrWhiteSpace())
{
query = query.Where(p => p.Name.Contains(searchedPhrase) ||
                                                       p.Alias.Contains(searchedPhrase) ||
                                                       p.Description.Contains(searchedPhrase));
}`

2022-02-20 21:56 UTC, mateuszgiedzinski commented on src/Patronage.DataAccess/Services/ProjectService.cs
> +            if (projectDto.Description == null) project.Description = project.Description;
project.Description = projectDto.Description is not null ? projectDto.Description.Data : project.Description;

2022-02-20 21:56 UTC, mateuszgiedzinski commented on src/Patronage.DataAccess/Services/ProjectService.cs
> +            if (projectDto.Description == null) project.Description = project.Description;
Podobnie zrobić z innymi polami.

2022-02-20 21:56 UTC, mateuszgiedzinski commented on src/Patronage.Api/Controllers/ProjectController.cs
> +        public async Task<ActionResult<IEnumerable<ProjectDto>>> GetAll([FromQuery] string? searchedPhrase)
Parameters swagger description is missing

2022-02-21 17:22 UTC, Archanial requested changes

2022-02-21 17:22 UTC, Archanial commented on src/Patronage.Api/Controllers/ProjectController.cs
> +                    "has been used to another project (these properties must be unique)"
```suggestion
                    Message = "Project with this id doesn't exist or you are trying to insert null value to property that is not nullable" +
                    "has been used to another project (these properties must be unique)"
```
Why are you concatenating strings?

2022-02-21 17:22 UTC, Archanial commented on src/Patronage.Api/MediatR/Projects/Commands/UpdateProjectCommand.cs
> +    public record UpdateProjectCommand(int id, UpdateProjectDto dto) : IRequest<bool>;
Isn't id already included in DTO?

2022-02-21 17:22 UTC, Archanial commented on src/Patronage.Api/Validators/Projects/UpdateProjectCommandValidator.cs
> +                    if (isAliasAlreadyTaken)
```suggestion
                    if (tableContext.Projects.Any(p => p.Alias == value))
```

2022-02-21 17:22 UTC, Archanial commented on src/Patronage.Api/Validators/Projects/UpdateProjectCommandValidator.cs
> +                    if (isNameAlreadyTaken)
```suggestion
                    if (tableContext.Projects.Any(p => p.Name == value);)
```

2022-02-21 17:22 UTC, Archanial commented on src/Patronage.DataAccess/Services/ProjectService.cs
> +            newProject.IsActive = projectDto.IsActive;
Instead of doing this just make constructor that takes those as arguments

2022-02-21 17:22 UTC, Archanial commented on src/Patronage.DataAccess/Services/ProjectService.cs
> +            else project.Description = projectDto.Description.Data;
```suggestion
            project.Description = projectDto.Description ?? project.Description.Data;
```
unsure how this will behave if dto is initialized with value 'null' but that's much clearer syntax.

2022-02-21 17:22 UTC, Archanial commented on src/Patronage.Models/Board.cs
> -        }
?

2022-02-21 17:22 UTC, Archanial commented on src/Patronage.Models/Project.cs
> +        public string? Description { get; set; }
Requires new migrations. Preferably made after #7 is merged

2022-02-22 09:48 UTC, Dimethiconol commented on src/Patronage.Api/MediatR/Projects/Commands/UpdateProjectCommand.cs
> +    public record UpdateProjectCommand(int id, UpdateProjectDto dto) : IRequest<bool>;
no

2022-02-22 09:59 UTC, Dimethiconol commented on src/Patronage.Models/Board.cs
> -        }
removeing the remnants of your bad implementation of ICratable and IModifable interfaces

2022-02-22 18:42 UTC, Archanial commented on src/Patronage.Models/Board.cs
> -        }
It's not bad implementation, it's consolidating expected function of this in interface.

2022-02-22 20:29 UTC, closed without merging